# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Build & Deploy

on:
  push:
    branches:
      - main
    paths:
      - '*.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run MAKE
      run: make all
      
    - name: Copy files for Web Job
      run: robocopy ./out '.\_wwwroot\App_Data\jobs\continuous\Beacons-DiscordBot\' /S
      
    - name: Zip files in Build Staging
      run: Compress-Archive .\_wwwroot\App_Data 'Beacons-DiscordBot-WebJob.zip'

    - name: Upload Artifact Beacons-DiscordBot-WebJob.zip
      uses: actions/upload-artifact@v2
      with:
        name: Beacons-DiscordBot-WebJob
        path: 'Beacons-DiscordBot-WebJob.zip'
        retention-days: 1
  
  deploy-staging:
    name: Deploy to Staging
    environment:
      name: Staging
      url: https://discord.com/oauth2/authorize?client_id=827762347112267778&scope=bot&permissions=150592
    runs-on: windows-latest
    needs: build
  
    steps:
    - name: Download Beacons-DiscordBot-WebJob
      uses: actions/download-artifact@v2
      with:
        name: Beacons-DiscordBot-WebJob
        path: '.\package'
        
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'alloploha'
        slot-name: 'staging'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4a1a4ed29043450cb8cf65ce4edb644c_STAGING_SLOT }}
        package: '.\package\Beacons-DiscordBot-WebJob.zip'
        
  deploy-production:
    name: Deploy to Production
    environment:
      name: Production
      url: https://discord.com/oauth2/authorize?client_id=826951404161335356&scope=bot&permissions=134208
    runs-on: windows-latest
    needs: deploy-staging
    
    steps:
    - name: Download Artifact Beacons-DiscordBot-WebApp
      uses: actions/download-artifact@v2
      with:
        name: Beacons-DiscordBot-WebJob
        path: '.\package'
    
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'alloploha'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4a1a4ed29043450cb8cf65ce4edb644c }}
        package: '.\package\Beacons-DiscordBot-WebJob.zip'
